# node:alpine is not used because the plugin-last-updated uses `git` and alpine
# does not have it.
version: '3'
services:
  vuepress:
    image: node
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    ports:
      - "8080:8080"
    command: ./scripts/dev.sh
    env_file: .env

  netlify:
    image: flemay/netlify
    volumes:
      - ./netlify.toml:/opt/app/netlify.toml:ro
      - ./docs/.vuepress/dist:/opt/app/docs/.vuepress/dist
      - ./scripts/deploy.sh:/opt/app/scripts/deploy.sh:ro
    working_dir: /opt/app
    env_file: .env